name: Check Markdown links

on:
  pull_request:
  push:
    branches:
    - main
  schedule:
  # Run everyday at 9:00 AM (See https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07)
  - cron: "0 9 * * *"

jobs:
  check-links:
    name: runner / linkspector
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@fc382e19892aca958e189954912fe379a8df270c # v1.2.4
        with:
          reporter: github-check
          fail_on_error: true
          config_file: '.github/config/.linkspector.yml'
          reviewdog_flags: '-fail-level=error'
          filter_mode: 'nofilter'
